### ISSUE TITLE
作者你好，很感谢你的开源

### ISSUE THREAD

**Issue by hqwlkj** [wanglu1209/NeteaseCloudMusic#10]
作者你好，很感谢你的开源

我是一个初学者，想请教一下 你的 model  是你手动写的还是用工具生成，有没有推荐的。我看官方有推荐但是我使用的时候失败了，尝试多次还是没有成功，始终缺少了 .g.dart  的文件。

**Comment by wanglu1209** [comment]
打开组织，里面有个项目是json_to_dart，超级好用
