### ISSUE TITLE
项目编译报错？

### ISSUE THREAD

**Issue by DarielChen** [wanglu1209/NeteaseCloudMusic#11]
Compiler message:
../../../flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-1.1.3/lib/src/cached_network_image_provider.dart:42:24: Error: The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.

**Comment by wanglu1209** [comment]
这不是项目的问题，是你本地环境和cached_network_image的问题。你可以去cached_network_image issue里查一下
