### ISSUE TITLE
在真机调试时，整个app都非常卡，掉帧严重

### ISSUE THREAD

**Issue by telami** [wanglu1209/NeteaseCloudMusic#13]
这个是flutter的问题么，是不是release版本会好点

**Comment by wanglu1209** [comment]
release 试试，debug 是很卡的。

debug 是 JIT，release 是 AOT，差距很大的。

**Comment by telami** [comment]
感谢光速回复，再请教一个问题，在用flutter ios --release 之后，怎么安装到iPhone上，是只能发布到AppStore，或者Testflight上么

如果可以，麻烦给我一个关键词，我去google一下

**Comment by wanglu1209** [comment]
iOS release 模式只能运行到真机。使用命令 flutter run --release 就可以了

**Comment by telami** [comment]
> iOS release 模式只能运行到真机。使用命令 flutter run --release 就可以了

明白，感谢
