### ISSUE TITLE
Android播放的时候经常黑屏闪退，大佬能解决一下吗？

### ISSUE THREAD

**Issue by xuelabi123** [wanglu1209/NeteaseCloudMusic#14]
用的小米手机，扫码蒲公英下载的

**Comment by wanglu1209** [comment]
。。。这么说我也不知道是什么问题呀，先说一下你是小米什么型号的手机？

然后我的建议是下载项目然后自己跑一下，看一下报错信息，因为我这不一定有对应型号的手机。。
