### ISSUE TITLE
下载了体验版，发现了一些问题

### ISSUE THREAD

**Issue by varenyzc** [wanglu1209/NeteaseCloudMusic#15]
1、加载图片慢，搜索数据慢，进入歌单页面慢，不知道是不是API的问题
2、从一个页面退回主页面的时候很卡，不知道是flutter的问题

**Comment by wanglu1209** [comment]
体验版那个接口是我跑在自己服务器上的，丐中丐版服务器，慢是肯定的😂
第二个问题，很卡，是怎么回事？是从哪个页面回去会比较卡？能否详细说一下

**Comment by varenyzc** [comment]
从歌曲播放界面跳回主界面
