### ISSUE TITLE
体验apk，卡顿掉帧很明显

### ISSUE THREAD

**Issue by taosimple** [wanglu1209/NeteaseCloudMusic#22]
你好！直接下载了体验apk，手机是小米8 android9，在首页左右切换，以及播放页返回，出现很明显的卡顿掉帧，这个apk是release版吗？还是flutter的问题，不知道可不可以优化，如果是这种性能不敢用在生产环境上

**Comment by wanglu1209** [comment]
图片所导致的内存问题，正在解决

**Comment by gaodeng** [comment]
release 模式下试了小米 9 SE  和 iPhone SE 

- 切换页面的时候掉帧比较严重。
- 动态页面滚动时间长的话，直接闪退了。
- 慢慢左右滑动切换页面的时候，顶部的 tab 动画有点抖
