### ISSUE TITLE
unnecessary_getters_setters

### ISSUE THREAD

**Issue by coolan2013** [wanglu1209/NeteaseCloudMusic#23]
vscode中有900多个提示信息，都与unnecessary_getters_setters有关，flutter中的实例是隐含有一个setter（不用final与const修饰时）与getter的，所以不需要用set与get重复定义setter与getter，浪费时间，作者可以注意一下。
       另外在华为荣耀7的机子上release版本速度还行，debug版本就比较慢了。

**Comment by wanglu1209** [comment]
好的，感谢提醒。我去搞一下看看
