### ISSUE TITLE
lib/utils/net_utils.dart:42:26: Error: Method not found: 'CookieManager'

### ISSUE THREAD

**Issue by chicwx** [wanglu1209/NeteaseCloudMusic#26]
Compiler message:
lib/utils/net_utils.dart:42:26: Error: Method not found: 'CookieManager'.
      ..interceptors.add(CookieManager(cj))
                         ^^^^^^^^^^^^^
lib/utils/net_utils.dart:47:32: Error: 'DefaultHttpClientAdapter' isn't a type.
    (_dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate =
                               ^^^^^^^^^^^^^^^^^^^^^^^^
lib/utils/custom_log_interceptor.dart:22:13: Error: No named parameter with the name 'logSize'.
            logSize: logSize);
            ^^^^^^^
../../../../xxx/Flutter/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image-0.7.2/lib/src/gesture/extended_image_slide_page_route.dart:333:9: Error: No named parameter with the name 'animation'.
        animation: animation,
        ^^^^^^^^^
../../../../xxx/Flutter/flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments don't match.
  CupertinoFullscreenDialogTransition({
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by chicwx** [comment]
有没有人遇到这个报错？

**Comment by wanglu1209** [comment]
适配了1.17.更新最新版本就好了
