### ISSUE TITLE
发现不止一个bug

### ISSUE THREAD

**Issue by dfaofeng** [wanglu1209/NeteaseCloudMusic#3]
播放界面退出后怎么重新进入,登录的时候密码错误也没提升,我还以为api接口没定义....还有"http://118.24.63.15/" 大佬应该用个测试服务器吧

**Comment by wanglu1209** [comment]
。。。功能还没写完呢，登录的逻辑就是简单的写了一下，
这个服务器是我自己的，readme里说了，运行项目的时候自己跑一个本地的啊。。。
我这服务器是最低配的。。

**Comment by wanglu1209** [comment]
我以后提交的时候还是把url改成127.0.0.1吧，不然好多人都不自己跑，我这服务器承受不住
