### ISSUE TITLE
Broken link in READMe

### ISSUE THREAD

**Issue by Tamir198** [wanglu1209/NeteaseCloudMusic#39]
When I click this link:

![image](https://user-images.githubusercontent.com/34707669/114343839-69915100-9b67-11eb-90da-dc2171035891.png)

I see this, I don't understand what it says but looks like 404 page:

![image](https://user-images.githubusercontent.com/34707669/114343946-9b0a1c80-9b67-11eb-8131-c7ae73bc7280.png)

**Comment by summeriver13** [comment]
![W36LUC1BHSQ(2UBDD13576E](https://github.com/fluttercandies/NeteaseCloudMusic/assets/83163060/fb9aeedd-7d82-4776-adc9-efd4fdf96926)
